language: python
python:
  - "2.7"
  - "3.5"

# GitHub branch
branches:
  only:
    - master

# install package and dependencies
install:
  - pip install -r requirements.txt
  - python setup.py install

# run unit tests
script:
  - coverage run setup.py pytest

# run coverage tests
after_success:
  - coveralls

# notification settings
notification:
  email: false
